--- 
abstract: parser of boolean expressions
author: Ruslan Zakirov <ruz@cpan.org>, Robert Spier <rspier@pobox.com>
build_requires: 
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Parse-BooleanLogic
no_index: 
  directory: 
    - inc
    - t
requires: 
  Regexp::Common: 0
version: 0.02
